[package]
name = "data_struct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.158"
serde_derive = "1.0.158"
csv = "1.2.1"
chrono = "0.4.24"
smartcore = "0.3.1"
